# Generated by Django 4.2.4 on 2023-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
